# Generated by Django 3.1.4 on 2021-03-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19App', '0002_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='mental_health',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('money', models.IntegerField()),
            ],
        ),
    ]
