# Generated by Django 3.1.4 on 2021-03-19 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covid19App', '0003_mental_health'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='economy',
            options={'verbose_name_plural': 'economy'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name_plural': 'education'},
        ),
        migrations.AlterModelOptions(
            name='mental_health',
            options={'verbose_name_plural': 'mental_health'},
        ),
        migrations.RenameField(
            model_name='economy',
            old_name='name',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='economy',
            old_name='money',
            new_name='gdp',
        ),
    ]
