# Generated by Django 3.1.4 on 2021-03-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19App', '0005_auto_20210319_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='economy20',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country20', models.CharField(max_length=220)),
                ('gdp20', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'economy20',
            },
        ),
    ]
